# Generated by Django 5.2.4 on 2025-07-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_participants_event_pdf_alter_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.URLField(help_text='Paste Google Maps link here'),
        ),
    ]
