# Generated by Django 5.2.4 on 2025-07-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_location_alter_event_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='Unknown', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='event_pdfs/'),
        ),
    ]
